*.*.log4j2.appenders=(directConsole);
*.*.log4j2.rootLogger.level=DEBUG;
*.*.log4j2.rootLogger.appenderRefs=(directConsole);
*.*.log4j2.appender.directConsole.type=Console;
*.*.log4j2.appender.directConsole.name=directConsole;
*.*.log4j2.appender.directConsole.layout.type=PatternLayout;
*.*.log4j2.appender.directConsole.layout.pattern="%d{HH:mm:ss.SSS} [%t] %-5p %C : %m%n";
